apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: default
spec:
  destination:
    namespace: default
    server: https://ub22arm001.mattwhitaker.co.uk:6443
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,codefresh-hosted-managed-cluster-default-cm.yaml,runtimes/codefresh-hosted/**/*.yaml,runtimes/codefresh-hosted/*.yaml}
      recurse: true
    path: resources
    repoURL: https://github.com/M-Whitaker/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
