gitops-runtime:
  global:
    codefresh:
      accountId: 6254b58e061479fbab563323
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
